import { TaxConfig } from '../hooks/useTaxConfig';

export interface DividendBand {
  label: string;
  rate: number;
  from: number;
  to: number;
  amount: number;
  allowanceUsed: number;
  taxable: number;
  tax: number;
}

export interface NonDivBand {
  label: string;
  rate: number;
  amount: number;
  tax: number;
}

export interface TaxResult {
  taperedPA: number;
  nonDivTax: number;
  divTax: number;
  nonDivBands: NonDivBand[];
  divBands: DividendBand[];
  totalAllSources: number;
}

/**
 * Computes income tax on two stacked income streams — non-dividend
 * (non-savings + savings, already net of any PSA-exempt amount) and
 * dividends — per UK stacking order (non-savings/savings first, dividends
 * on top). Personal allowance taper is tested against combined income
 * across BOTH streams, but its cost always lands on the non-dividend
 * stream (whichever sits at the bottom of the stack): dividends are never
 * charged an inflated "taper rate", only the plain nominal band rate for
 * wherever in the total-income stack they land.
 *
 * nonDivGross: non-savings + savings income, already net of psaExempt.
 * divGross: dividend income (gross, before the dividend allowance).
 */
export function computeTax(config: TaxConfig, nonDivGross: number, divGross: number): TaxResult {
  const { B0, B1, B2, B3, TR_B, TR_H, TR_A, DIVIDEND_ALLOWANCE, DIV_ORDINARY, DIV_UPPER, DIV_ADDITIONAL } = config;
  const trb = TR_B / 100;

  const totalAllSources = nonDivGross + divGross;
  const taperedPA = Math.max(0, Math.min(B0, B0 - Math.max(0, totalAllSources - B2) / 2));

  // ─── Non-dividend leg: plain bands, no special 60% case — the taper is
  // modelled explicitly via taperedPA rather than via a flat elevated rate,
  // so it correctly triggers even when nonDivGross alone is under B2 but
  // totalAllSources (inclusive of dividends) is not. ──────────────────────
  const nonDivTaxable = Math.max(0, nonDivGross - taperedPA);
  const basicWidth = B1 - B0;
  const higherWidth = B3 - B1 + B0; // absorbs the taper "overshoot" — reproduces the old 60%-band trick exactly
  const inBasic = Math.min(nonDivTaxable, basicWidth);
  const inHigher = Math.min(Math.max(0, nonDivTaxable - basicWidth), higherWidth);
  const inAddl = Math.max(0, nonDivTaxable - basicWidth - higherWidth);
  const basicRate = TR_B;
  const higherRate = TR_B + TR_H;
  const addlRate = TR_B + TR_A;
  const nonDivBands: NonDivBand[] = [
    { label: 'Basic rate', rate: basicRate, amount: inBasic, tax: inBasic * trb },
    { label: 'Higher rate', rate: higherRate, amount: inHigher, tax: inHigher * (higherRate / 100) },
    { label: 'Additional rate', rate: addlRate, amount: inAddl, tax: inAddl * (addlRate / 100) },
  ];
  const nonDivTax = nonDivBands.reduce((sum, b) => sum + b.tax, 0);

  // ─── Dividend leg: stacks on top of nonDivGross in total-income terms.
  // Zones are defined by the standard band boundaries; the £0 zone below
  // taperedPA reflects any personal allowance left unused by the
  // non-dividend stream (only relevant when nonDivGross < taperedPA,
  // e.g. a low-salary/high-dividend company director). ─────────────────
  const divStart = nonDivGross;
  const divEnd = totalAllSources;
  const zones: Array<{ lo: number; hi: number; rate: number; label: string }> = [
    { lo: 0, hi: taperedPA, rate: 0, label: 'Unused personal allowance' },
    { lo: taperedPA, hi: B1, rate: DIV_ORDINARY, label: 'Ordinary dividend rate' },
    { lo: B1, hi: B3, rate: DIV_UPPER, label: 'Upper dividend rate' },
    { lo: B3, hi: Infinity, rate: DIV_ADDITIONAL, label: 'Additional dividend rate' },
  ];

  let remainingAllowance = DIVIDEND_ALLOWANCE;
  let divTax = 0;
  const divBands: DividendBand[] = [];

  for (const zone of zones) {
    const lo = Math.max(divStart, zone.lo);
    const hi = Math.min(divEnd, zone.hi);
    const amount = Math.max(0, hi - lo);
    if (amount <= 0) continue;

    if (zone.rate === 0) {
      divBands.push({ label: zone.label, rate: 0, from: lo, to: hi, amount, allowanceUsed: 0, taxable: 0, tax: 0 });
      continue;
    }

    const allowanceUsed = Math.min(amount, remainingAllowance);
    remainingAllowance -= allowanceUsed;
    const taxable = amount - allowanceUsed;
    const tax = taxable * (zone.rate / 100);
    divTax += tax;
    divBands.push({ label: zone.label, rate: zone.rate, from: lo, to: hi, amount, allowanceUsed, taxable, tax });
  }

  return { taperedPA, nonDivTax, divTax, nonDivBands, divBands, totalAllSources };
}

export interface AdditionalReliefResult {
  nonDivRelief: number;
  divRelief: number;
  total: number;
  atTop: TaxResult;
  atBottom: TaxResult;
}

/**
 * Additional relief (self-assessment refund) generated by a contribution
 * that reduces nonDivTop by nonDivReduction, computed as the tax
 * difference between the top and bottom of that reduction — minus the
 * basic-rate relief already given at source. Using a diff-of-computeTax
 * rather than hand-derived band arithmetic means the personal-allowance
 * restoration effect and any dividend-band-shift effect (a contribution
 * pulling the boundary beneath the dividend layer down, dropping dividend
 * slices into a lower rate) fall out automatically.
 *
 * The at-source correction is subtracted against the TAXABLE reduction
 * (derived from nonDivBands, which floors at zero once income drops below
 * the personal allowance), not the raw (nonDivTop - bottom) gross
 * reduction. Subtracting against the raw reduction would keep deducting
 * 20% even for the portion of a very large contribution that dips into the
 * tax-free personal allowance — where no tax was ever being paid, so there
 * is nothing to correct for — driving nonDivRelief negative for large
 * contributions instead of correctly plateauing once the higher/additional
 * rate bands are fully vacated.
 */
export function calculateAdditionalRelief(
  config: TaxConfig,
  nonDivTop: number,
  nonDivReduction: number,
  divIncome: number
): AdditionalReliefResult {
  const trb = config.TR_B / 100;
  const top = Math.max(0, nonDivTop);
  const bottom = Math.max(0, Math.min(top, top - nonDivReduction));
  const atTop = computeTax(config, top, divIncome);
  const atBottom = computeTax(config, bottom, divIncome);
  const topTaxable = atTop.nonDivBands.reduce((s, b) => s + b.amount, 0);
  const bottomTaxable = atBottom.nonDivBands.reduce((s, b) => s + b.amount, 0);
  const taxableReduction = topTaxable - bottomTaxable;
  const nonDivRelief = (atTop.nonDivTax - atBottom.nonDivTax) - trb * taxableReduction;
  const divRelief = atTop.divTax - atBottom.divTax;
  return { nonDivRelief, divRelief, total: nonDivRelief + divRelief, atTop, atBottom };
}
